version: '3.8'

services:
  mariadb:
    container_name: mariadb-grics
    image: docker.io/bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=user
      - MARIADB_DATABASE=db
    ports:
      - '3306:3306'  # Asegúrate de exponer el puerto si necesitas acceder desde fuera de Docker

  myapp:
    container_name: myapp-grics
    image: docker.io/bitnami/laravel:latest
    ports:
      - '8000:8000'
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=db
      - DB_USERNAME=user
      - DB_PASSWORD=
    volumes:
      - './project:/app'
    depends_on:
      - mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-grics
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=user
      - PMA_PASSWORD=
    depends_on:
      - mariadb

